sozler = [

    ["Gelecek, bugünden hazırlanan bir yerdir.","Malcolm X"],
    ["Başarı, küçük çabaların tekrar tekrar tekrarlanmasından doğar.","Robert Collier"],
    ["Eğitimdir ki bir milleti ya özgür, bağımsız, şanlı, yüksek bir topluluk halinde yaşatır ya da esaret ve sefalete terk eder.","Mustafa Kemal Atatürk"],
    ["En büyük zafer, düşmemekte değil, her düştüğünde ayağa kalkmaktır.","Vince Lombardi"],
    ["Kendinize inanın ve ne olursa olsun devam edin.","Walt Disney"],
    ["Hayatta en hakiki mürşit ilimdir.","Mustafa Kemal Atatürk"],
    ["Zorluklar, insanın kendini keşfetmesi için bir fırsattır.","Ralph Waldo Emerson"],
    ["Hedeflerinizden asla vazgeçmeyin.","Albert Einstein"],
    ["Zafer, 'zafer benimdir' diyebilenlerindir.","Mustafa Kemal Atatürk"],
    ["Başarının sırrı, sürekli olarak öğrenmektir.","John C. Maxwell"],
    ["Yapabileceğinize inandığınızda, başaramayacağınız hiçbir şey yoktur.","Mary Kay Ash"],
    ["Milletimizin geleceği, bugünkü gençlerin doğru görüşü ve yorulmak bilmeyen çalışma azmi ile büyük ve parlak olacaktır.","Mustafa Kemal Atatürk"],
    ["Hayatınızı hayalleriniz doğrultusunda yaşayın.","Les Brown"],
    ["Kendinize bir hedef belirleyin ve ona ulaşmak için çalışın.","Bruce Lee"],
    ["Vatanını en çok seven, görevini en iyi yapandır.","Mustafa Kemal Atatürk"],
    ["Başarı, hazırlık ve fırsatın birleştiği noktadır.","Bobby Unser"],
    ["Düşüncelerinize dikkat edin; onlar sözlerinize dönüşür.","Mahatma Gandhi"],
    ["Hayatta en önemli şey, kendinizi tanımaktır.","Socrates"],
    ["Egemenlik kayıtsız şartsız milletindir.","Mustafa Kemal Atatürk"],
    ["Başarı, cesaretin ödülüdür.","George S. Patton"],
    ["Yarın, bugünden yaptıklarınızın sonucudur.","Mahatma Gandhi"],
    ["Başarı, hayallerinizin peşinden gitmekle başlar.","Paulo Coelho"],
    ["Yapabileceğiniz en büyük yatırım, kendinize yaptığınız yatırımdır.","Warren Buffett"],
    ["Yüksel Türk! Senin için yüksekliğin sınırı yoktur.","Mustafa Kemal Atatürk"],
    ["Başarı, kararlılıkla çalışmanın sonucudur.","Colin Powell"],
    ["Hayallerinizin peşinden gitmek, en büyük cesareti gerektirir.","Oprah Winfrey"],
    ["İnsanı yenilgi değil, vazgeçiş bitirir.","Richard Nixon"],
    ["Başarı, azim ve kararlılıkla gelir.","Conrad Hilton"],
    ["Hayatta en önemli şey, neyin peşinden gittiğinizdir.","Joseph Campbell"],
    ["Beni görmek demek mutlaka yüzümü görmek değildir. Benim fikirlerimi, benim duygularımı anlıyorsanız ve hissediyorsanız bu kafidir.","Mustafa Kemal Atatürk"],
    ["Başarıya giden yol, sürekli olarak bir hedefe odaklanmaktan geçer.","Vince Lombardi"],
    ["Başarı, başkalarının imkansız olduğunu düşündüğü şeyleri yapmaktır.","Walter Bagehot"],
    ["Gerçek başarı, mutluluğun peşinden gitmekle başlar.","Helen Keller"],
    ["Zorluklar, karşımıza çıkmak için değil, aşılmak için vardır.","Albert Schweitzer"],
    ["Yapabileceğinize inandığınızda, yolun yarısını zaten kat etmişsinizdir.","Theodore Roosevelt"],
    ["Kendinize inanmadıkça, hiç kimseye inanamazsınız.","Dorothy Day"],
    ["Hedefleriniz için çalıştığınızda, hayalleriniz gerçeğe dönüşür.","Les Brown"],
    ["Cesaret, korkuya rağmen devam edebilmektir.","Franklin D. Roosevelt"],
    ["Başarısızlık, başarıya giden en emin yoldur.","Thomas Edison"],
    ["Küçük adımlarla büyük işler başarılır.","Laozi"],
    ["Hayallerinizin peşinden gidin, çünkü başka bir yolunuz yok.","James Cameron"],
    ["Hayatın anlamı, neyin peşinden gittiğinizde saklıdır.","Joseph Campbell"],
    ["Düşüncelerinize dikkat edin; onlar sözlerinize dönüşür.","Mahatma Gandhi"],
    ["Başarı, hazırlık ve fırsatın birleştiği noktadır.","Bobby Unser"],
    ["Kendinize bir hedef belirleyin ve ona ulaşmak için çalışın.","Bruce Lee"],
    ["En büyük zaferimiz, hiç düşmemekte değil, her düştüğümüzde ayağa kalkmaktır.","Confucius"],
    ["Hayatta en önemli şey, kendinizi tanımaktır.","Socrates"],
    ["Başarının sırrı, pes etmemekte yatar.","Winston Churchill"],
    ["Yapabileceğinize inandığınızda, başaramayacağınız şey yoktur.","Mary Kay Ash"],
    ["Başarı, tutkularınızın peşinden gitmektir.","Oprah Winfrey"],
    ["Hayatınızı değiştirmek için asla geç değildir.","Jane Fonda"],
    ["Başarı, her gün küçük adımlar atarak gelir.","Robert Collier"],
    ["Düşünceleriniz, geleceğinizi şekillendirir.","Norman Vincent Peale"],
    ["Kendinizi sürekli geliştirerek başarıya ulaşabilirsiniz.","Tony Robbins"],
    ["Başarı, cesaretin ödülüdür.","George S. Patton"],
    ["Yarın, bugünden yaptıklarınızın sonucudur.","Mahatma Gandhi"],
    ["Başarı, hayallerinizin peşinden gitmekle başlar.","Paulo Coelho"],
    ["Yapabileceğiniz en büyük yatırım, kendinize yaptığınız yatırımdır.","Warren Buffett"],
    ["Başarı, kararlılıkla çalışmanın sonucudur.","Colin Powell"],
    ["Hayallerinizin peşinden gitmek, en büyük cesareti gerektirir.","Oprah Winfrey"]
]